#!/bin/bash
#set -e

# software from AUR (Arch User Repositories)
# https://aur.archlinux.org/packages/


echo "Installing category Accessories"
sh AUR/install-cool-retro-term-v*.sh

echo "Installing category Development"
sh AUR/install-sublime-text-v*.sh

echo "Installing category System"
sh AUR/install-arc-gtk-theme-git-v*.sh
sh AUR/install-neofetch-v*.sh
sh AUR/install-numix-circle-icon-theme-git-v*.sh
sh AUR/install-pamac-aur-v*.sh
sh AUR/install-paper-icon-theme-git-v*.sh
sh AUR/install-papirus-icon-theme-git-v*.sh
sh AUR/install-sardi-icons-v*.sh
sh AUR/install-sardi-extra-icons-v*.sh
sh AUR/install-screenkey-v*.sh
sh AUR/install-surfn-icons-git-v*.sh
sh AUR/install-ttf-font-awesome-v*.sh
sh AUR/install-ttf-mac-fonts-v*.sh
sh AUR/install-virtualbox-for-linux-kernel-v*.sh
sh AUR/install-xcursor-breeze-v*.sh


# these come last always

sh AUR/install-hardcode-fixer-git-v*.sh
sudo hardcode-fixer

echo "################################################################"
echo "####        Software from AUR Repository installed        ######"
echo "################################################################"
